ABODDetector_OutlierDetectionNeighbors = ["outlier_detection"]
ABODDetector_OutlierDetectionPython = ["outlier_detection"]
AEDetector_OutlierDetectionNetworks = ["outlier_detection"]
ARDRegressor_ScikitLearn = ["regression", "Bayesian_models"]
AdaBoostClassifier_ScikitLearn = ["classification"]
AdaBoostRegressor_ScikitLearn = ["regression"]
AdaBoostStumpClassifier_DecisionTree = ["classification"]
AffinityPropagation_ScikitLearn = ["clustering"]
AgglomerativeClustering_ScikitLearn = ["clustering", "static_models"]
BM25Transformer_MLJText = ["encoders", "text_analysis"]
BaggingClassifier_ScikitLearn = ["classification", "ensemble_models"]
BaggingRegressor_ScikitLearn = ["regression", "ensemble_models"]
BayesianLDA_MultivariateStats = ["dimension_reduction", "classification", "Bayesian_models"]
BayesianLDA_ScikitLearn = ["dimension_reduction", "classification", "Bayesian_models"]
BayesianQDA_ScikitLearn = ["dimension_reduction", "classification", "Bayesian_models"]
BayesianRidgeRegressor_ScikitLearn = ["regression", "Bayesian_models"]
BayesianSubspaceLDA_MultivariateStats = ["dimension_reduction", "classification", "Bayesian_models"]
BernoulliNBClassifier_ScikitLearn = ["classification", "Bayesian_models"]
Birch_ScikitLearn = ["clustering", "dimension_reduction", ]
CBLOFDetector_OutlierDetectionPython = ["outlier_detection"]
COFDetector_OutlierDetectionNeighbors = ["outlier_detection"]
COFDetector_OutlierDetectionPython = ["outlier_detection"]
COPODDetector_OutlierDetectionPython = ["outlier_detection"]
ComplementNBClassifier_ScikitLearn = ["classification", "Bayesian_models"]
ConstantClassifier_MLJModels = ["classification"]
ConstantRegressor_MLJModels = ["regression"]
ContinuousEncoder_MLJModels = ["encoders"]
CountTransformer_MLJText = ["text_analysis", "encoders"]
DBSCAN_Clustering = ["clustering", "static_models"]
DBSCAN_ScikitLearn = ["clustering", "static_models"]
DNNDetector_OutlierDetectionNeighbors = ["outlier_detection"]
DSADDetector_OutlierDetectionNetworks = ["outlier_detection"]
DecisionTreeClassifier_BetaML = ["classification"]
DecisionTreeClassifier_DecisionTree = ["classification"]
DecisionTreeRegressor_BetaML = ["regression"]
DecisionTreeRegressor_DecisionTree = ["regression"]
DeterministicConstantClassifier_MLJModels = ["classification"]
DeterministicConstantRegressor_MLJModels = ["regression"]
DummyClassifier_ScikitLearn = ["classification"]
DummyRegressor_ScikitLearn = ["regression"]
ESADDetector_OutlierDetectionNetworks = ["outlier_detection"]
ElasticNetCVRegressor_ScikitLearn = ["regression"]
ElasticNetRegressor_MLJLinearModels = ["regression"]
ElasticNetRegressor_ScikitLearn = ["regression"]
EpsilonSVR_LIBSVM = ["regression"]
EvoLinearRegressor_EvoLinear = ["regression"]
EvoTreeClassifier_EvoTrees = ["classification", "iterative_models"]
EvoTreeCount_EvoTrees = ["regression", "iterative_models"]
EvoTreeGaussian_EvoTrees = ["regression", "iterative_models"]
EvoTreeMLE_EvoTrees = ["regression", "iterative_models"]
EvoTreeRegressor_EvoTrees = ["regression", "iterative_models"]
ExtraTreesClassifier_ScikitLearn = ["classification", "iterative_models"]
ExtraTreesRegressor_ScikitLearn = ["regression", "iterative_models"]
FactorAnalysis_MultivariateStats = ["dimension_reduction", ]
FeatureAgglomeration_ScikitLearn = ["clustering", "static_models"]
FeatureSelector_MLJModels = ["dimension_reduction", ]
FillImputer_MLJModels = ["missing_value_imputation", ]
GaussianMixtureClusterer_BetaML = ["clustering", "distribution_fitter"]
GaussianMixtureImputer_BetaML = ["missing_value_imputation", "distribution_fitter"]
GaussianMixtureRegressor_BetaML = ["regression", "distribution_fitter"]
GaussianNBClassifier_NaiveBayes = ["classification", "Bayesian_models"]
GaussianNBClassifier_ScikitLearn = ["classification", "Bayesian_models"]
GaussianProcessClassifier_ScikitLearn = ["classification", "Bayesian_models"]
GaussianProcessRegressor_ScikitLearn = ["regression", "Bayesian_models"]
GeneralImputer_BetaML = ["missing_value_imputation", ]
GradientBoostingClassifier_ScikitLearn = ["classification"]
GradientBoostingRegressor_ScikitLearn = ["regression"]
HBOSDetector_OutlierDetectionPython = ["outlier_detection"]
HierarchicalClustering_Clustering = ["clustering"]
HuberRegressor_MLJLinearModels = ["regression"]
HuberRegressor_ScikitLearn = ["regression"]
ICA_MultivariateStats = ["encoders"]
IForestDetector_OutlierDetectionPython = ["outlier_detection"]
ImageClassifier_MLJFlux = ["classification", "image_processing", "iterative_models"]
InteractionTransformer_MLJModels = ["static_models"]
KMeans_BetaML = ["clustering"]
KMeans_Clustering = ["clustering", "dimension_reduction", ]
KMeans_ParallelKMeans = ["clustering", "dimension_reduction", ]
KMeans_ScikitLearn = ["clustering", "dimension_reduction", ]
KMedoids_BetaML = ["clustering"]
KMedoids_Clustering = ["clustering", "dimension_reduction", ]
KNNClassifier_NearestNeighborModels = ["classification"]
KNNDetector_OutlierDetectionNeighbors = ["outlier_detection"]
KNNDetector_OutlierDetectionPython = ["outlier_detection"]
KNNRegressor_NearestNeighborModels = ["regression"]
KNeighborsClassifier_ScikitLearn = ["classification"]
KNeighborsRegressor_ScikitLearn = ["regression"]
KPLSRegressor_PartialLeastSquaresRegressor = ["regression"]
KernelPCA_MultivariateStats = ["dimension_reduction", ]
KernelPerceptron_BetaML = ["classification"]
LADRegressor_MLJLinearModels = ["regression"]
LDA_MultivariateStats = ["classification", "dimension_reduction", ]
LGBMClassifier_LightGBM = ["classification", "iterative_models"]
LGBMRegressor_LightGBM = ["regression", "iterative_models"]
LMDDDetector_OutlierDetectionPython = ["outlier_detection", "outlier_detection"]
LOCIDetector_OutlierDetectionPython = ["outlier_detection"]
LODADetector_OutlierDetectionPython = ["outlier_detection"]
LOFDetector_OutlierDetectionNeighbors = ["outlier_detection"]
LOFDetector_OutlierDetectionPython = ["outlier_detection"]
LarsCVRegressor_ScikitLearn = ["regression"]
LarsRegressor_ScikitLearn = ["regression"]
LassoCVRegressor_ScikitLearn = ["regression"]
LassoLarsCVRegressor_ScikitLearn = ["regression"]
LassoLarsICRegressor_ScikitLearn = ["regression"]
LassoLarsRegressor_ScikitLearn = ["regression"]
LassoRegressor_MLJLinearModels = ["regression"]
LassoRegressor_ScikitLearn = ["regression"]
LinearBinaryClassifier_GLM = ["classification"]
LinearCountRegressor_GLM = ["regression"]
LinearPerceptron_BetaML = ["classification"]
LinearRegressor_GLM = ["regression"]
LinearRegressor_MLJLinearModels = ["regression"]
LinearRegressor_MultivariateStats = ["regression"]
LinearRegressor_ScikitLearn = ["regression"]
LinearSVC_LIBSVM = ["classification"]
LogisticCVClassifier_ScikitLearn = ["classification"]
LogisticClassifier_MLJLinearModels = ["classification"]
LogisticClassifier_ScikitLearn = ["classification"]
MCDDetector_OutlierDetectionPython = ["outlier_detection", "outlier_detection"]
MeanShift_ScikitLearn = ["clustering"]
MiniBatchKMeans_ScikitLearn = ["clustering", "dimension_reduction", ]
MultiTaskElasticNetCVRegressor_ScikitLearn = ["regression"]
MultiTaskElasticNetRegressor_ScikitLearn = ["regression"]
MultiTaskLassoCVRegressor_ScikitLearn = ["regression"]
MultiTaskLassoRegressor_ScikitLearn = ["regression"]
MultinomialClassifier_MLJLinearModels = ["classification"]
MultinomialNBClassifier_NaiveBayes = ["classification", "Bayesian_models"]
MultinomialNBClassifier_ScikitLearn = ["classification", "Bayesian_models"]
MultitargetGaussianMixtureRegressor_BetaML = ["regression", "distribution_fitter"]
MultitargetKNNClassifier_NearestNeighborModels = ["classification"]
MultitargetKNNRegressor_NearestNeighborModels = ["regression"]
MultitargetLinearRegressor_MultivariateStats = ["regression"]
MultitargetNeuralNetworkRegressor_BetaML = ["regression"]
MultitargetNeuralNetworkRegressor_MLJFlux = ["regression", "iterative_models"]
MultitargetRidgeRegressor_MultivariateStats = ["regression"]
NeuralNetworkClassifier_BetaML = ["classification"]
NeuralNetworkClassifier_MLJFlux = ["classification", "iterative_models"]
NeuralNetworkRegressor_BetaML = ["regression"]
NeuralNetworkRegressor_MLJFlux = ["regression", "iterative_models"]
NuSVC_LIBSVM = ["classification"]
NuSVR_LIBSVM = ["regression"]
OCSVMDetector_OutlierDetectionPython = ["outlier_detection"]
OPTICS_ScikitLearn = ["clustering", "static_models"]
OneClassSVM_LIBSVM = ["outlier_detection"]
OneHotEncoder_MLJModels = ["encoders"]
OneRuleClassifier_OneRule = ["classification"]
OrthogonalMatchingPursuitCVRegressor_ScikitLearn = ["regression"]
OrthogonalMatchingPursuitRegressor_ScikitLearn = ["regression"]
PCA_MultivariateStats = ["dimension_reduction", ]
PCADetector_OutlierDetectionPython = ["outlier_detection"]
PLSRegressor_PartialLeastSquaresRegressor = ["regression"]
PPCA_MultivariateStats = ["dimension_reduction"]
PassiveAggressiveClassifier_ScikitLearn = ["classification"]
PassiveAggressiveRegressor_ScikitLearn = ["regression"]
Pegasos_BetaML = ["classification"]
PerceptronClassifier_ScikitLearn = ["classification"]
ProbabilisticSGDClassifier_ScikitLearn = ["classification"]
QuantileRegressor_MLJLinearModels = ["regression"]
RANSACRegressor_ScikitLearn = ["regression"]
RODDetector_OutlierDetectionPython = ["outlier_detection"]
RandomForestClassifier_BetaML = ["classification", "ensemble_models", "iterative_models"]
RandomForestClassifier_DecisionTree = ["classification", "ensemble_models", "iterative_models"]
RandomForestClassifier_ScikitLearn = ["classification", "ensemble_models", "iterative_models"]
RandomForestImputer_BetaML = ["missing_value_imputation", "ensemble_models", "iterative_models"]
RandomForestRegressor_BetaML = ["regression", "ensemble_models", "iterative_models"]
RandomForestRegressor_DecisionTree = ["regression", "ensemble_models", "iterative_models"]
RandomForestRegressor_ScikitLearn = ["regression", "ensemble_models", "iterative_models"]
RidgeCVClassifier_ScikitLearn = ["classification"]
RidgeCVRegressor_ScikitLearn = ["classification"]
RidgeClassifier_ScikitLearn = ["classification"]
RidgeRegressor_MLJLinearModels = ["regression"]
RidgeRegressor_MultivariateStats = ["regression"]
RidgeRegressor_ScikitLearn = ["regression"]
RobustRegressor_MLJLinearModels = ["regression"]
SGDClassifier_ScikitLearn = ["classification"]
SGDRegressor_ScikitLearn = ["regression"]
SODDetector_OutlierDetectionPython = ["outlier_detection", "outlier_detection"]
SOSDetector_OutlierDetectionPython = ["outlier_detection"]
SVC_LIBSVM = ["classification"]
SVMClassifier_ScikitLearn = ["classification"]
SVMLinearClassifier_ScikitLearn = ["classification"]
SVMLinearRegressor_ScikitLearn = ["regression"]
SVMNuClassifier_ScikitLearn = ["classification"]
SVMNuRegressor_ScikitLearn = ["regression"]
SVMRegressor_ScikitLearn = ["regression"]
SimpleImputer_BetaML = ["missing_value_imputation"]
SpectralClustering_ScikitLearn = ["clustering", "static_models"]
Standardizer_MLJModels = ["encoders"]
SubspaceLDA_MultivariateStats = ["classification", "dimension_reduction"]
TSVDTransformer_TSVD = ["dimension_reduction"]
TfidfTransformer_MLJText = ["encoders", "text_analysis"]
TheilSenRegressor_ScikitLearn = ["regression"]
UnivariateBoxCoxTransformer_MLJModels = ["encoders"]
UnivariateDiscretizer_MLJModels = ["encoders"]
UnivariateFillImputer_MLJModels = ["missing_value_imputation"]
UnivariateStandardizer_MLJModels = ["encoders"]
UnivariateTimeTypeToContinuous_MLJModels = ["encoders"]
XGBoostClassifier_XGBoost = ["classification", "iterative_models", "ensemble_models"]
XGBoostCount_XGBoost = ["regression", "iterative_models", "ensemble_models"]
XGBoostRegressor_XGBoost = ["regression", "iterative_models", "ensemble_models"]
