ABODDetector_OutlierDetectionNeighbors = ["outlier_detection"]
ABODDetector_OutlierDetectionPython = ["outlier_detection"]
AEDetector_OutlierDetectionNetworks = ["outlier_detection"]
ARDRegressor_MLJScikitLearnInterface = ["regression", "Bayesian_models"]
AdaBoostClassifier_MLJScikitLearnInterface = ["classification"]
AdaBoostRegressor_MLJScikitLearnInterface = ["regression"]
AdaBoostStumpClassifier_DecisionTree = ["classification"]
AffinityPropagation_MLJScikitLearnInterface = ["clustering"]
AgglomerativeClustering_MLJScikitLearnInterface = ["clustering", "static_models"]
AutoEncoder_BetaML = ["dimension_reduction"]
BM25Transformer_MLJText = ["encoders", "text_analysis"]
BaggingClassifier_MLJScikitLearnInterface = ["classification", "ensemble_models"]
BaggingRegressor_MLJScikitLearnInterface = ["regression", "ensemble_models"]
BalancedBaggingClassifier_MLJBalancing = ["class_imbalance", "classification", "meta_algorithms"]
BinaryThresholdPredictor_MLJModels = ["meta_algorithms", "classification"]
BalancedModel_MLJBalancing = ["class_imbalance", "meta_algorithms"]
BayesianLDA_MultivariateStats = ["dimension_reduction", "classification", "Bayesian_models"]
BayesianLDA_MLJScikitLearnInterface = ["dimension_reduction", "classification", "Bayesian_models"]
BayesianQDA_MLJScikitLearnInterface = ["dimension_reduction", "classification", "Bayesian_models"]
BayesianRidgeRegressor_MLJScikitLearnInterface = ["regression", "Bayesian_models"]
BayesianSubspaceLDA_MultivariateStats = ["dimension_reduction", "classification", "Bayesian_models"]
BernoulliNBClassifier_MLJScikitLearnInterface = ["classification", "Bayesian_models"]
Birch_MLJScikitLearnInterface = ["clustering", "dimension_reduction", ]
BisectingKMeans_MLJScikitLearnInterface = ["clustering", "dimension_reduction", ]
BorderlineSMOTE1_Imbalance = ["class_imbalance"]
CatBoostClassifier_CatBoost = ["classification", "ensemble_models", "iterative_models"]
CatBoostRegressor_CatBoost = ["regression", "ensemble_models", "iterative_models"]
CBLOFDetector_OutlierDetectionPython = ["outlier_detection"]
CDDetector_OutlierDetectionPython = ["outlier_detection"]
ClusterUndersampler_Imbalance = ["class_imbalance"]
COFDetector_OutlierDetectionNeighbors = ["outlier_detection"]
COFDetector_OutlierDetectionPython = ["outlier_detection"]
COPODDetector_OutlierDetectionPython = ["outlier_detection"]
ComplementNBClassifier_MLJScikitLearnInterface = ["classification", "Bayesian_models"]
ConstantClassifier_MLJModels = ["classification"]
ConstantRegressor_MLJModels = ["regression"]
ContinuousEncoder_MLJModels = ["encoders"]
CountTransformer_MLJText = ["text_analysis", "encoders"]
DBSCAN_Clustering = ["clustering", "static_models"]
DBSCAN_MLJScikitLearnInterface = ["clustering", "static_models"]
DNNDetector_OutlierDetectionNeighbors = ["outlier_detection"]
DSADDetector_OutlierDetectionNetworks = ["outlier_detection"]
DecisionTreeClassifier_BetaML = ["classification"]
DecisionTreeClassifier_DecisionTree = ["classification"]
DecisionTreeRegressor_BetaML = ["regression"]
DecisionTreeRegressor_DecisionTree = ["regression"]
DeterministicConstantClassifier_MLJModels = ["classification"]
DeterministicConstantRegressor_MLJModels = ["regression"]
DummyClassifier_MLJScikitLearnInterface = ["classification"]
DummyRegressor_MLJScikitLearnInterface = ["regression"]
ECODDetector_OutlierDetectionPython = ["outlier_detection"]
ESADDetector_OutlierDetectionNetworks = ["outlier_detection"]
ElasticNetCVRegressor_MLJScikitLearnInterface = ["regression"]
ElasticNetRegressor_MLJLinearModels = ["regression"]
ElasticNetRegressor_MLJScikitLearnInterface = ["regression"]
ENNUndersampler_Imbalance = ["class_imbalance"]
EnsembleModel_MLJEnsembles = ["ensemble_models", "meta_algorithms"]
EpsilonSVR_LIBSVM = ["regression"]
EvoLinearRegressor_EvoLinear = ["regression"]
EvoTreeClassifier_EvoTrees = ["classification", "ensemble_models", "iterative_models"]
EvoTreeCount_EvoTrees = ["regression", "ensemble_models", "iterative_models"]
EvoTreeGaussian_EvoTrees = ["regression", "ensemble_models", "iterative_models"]
EvoTreeMLE_EvoTrees = ["regression", "ensemble_models", "iterative_models"]
EvoTreeRegressor_EvoTrees = ["regression", "ensemble_models", "iterative_models"]
EvoSplineRegressor_EvoLinear = ["regression", "ensemble_models", "iterative_models"]
ExtraTreesClassifier_MLJScikitLearnInterface = ["classification", "iterative_models"]
ExtraTreesRegressor_MLJScikitLearnInterface = ["regression", "iterative_models"]
FactorAnalysis_MultivariateStats = ["dimension_reduction", ]
FeatureAgglomeration_MLJScikitLearnInterface = ["clustering", "static_models", "feature_engineering"]
FeatureSelector_FeatureSelection = ["dimension_reduction", "feature_engineering"]
FillImputer_MLJModels = ["missing_value_imputation", ]
GaussianMixtureClusterer_BetaML = ["clustering", "density_estimation"]
GaussianMixtureImputer_BetaML = ["missing_value_imputation", "density_estimation"]
GaussianMixtureRegressor_BetaML = ["regression", "density_estimation"]
GaussianNBClassifier_NaiveBayes = ["classification", "Bayesian_models"]
GaussianNBClassifier_MLJScikitLearnInterface = ["classification", "Bayesian_models"]
GaussianProcessClassifier_MLJScikitLearnInterface = ["classification", "Bayesian_models"]
GaussianProcessRegressor_MLJScikitLearnInterface = ["regression", "Bayesian_models"]
GeneralImputer_BetaML = ["missing_value_imputation", ]
GradientBoostingClassifier_MLJScikitLearnInterface = ["classification"]
GradientBoostingRegressor_MLJScikitLearnInterface = ["regression"]
GMMDetector_OutlierDetectionPython = ["outlier_detection"]
HBOSDetector_OutlierDetectionPython = ["outlier_detection"]
HDBSCAN_MLJScikitLearnInterface = ["clustering", "static_models"]
HierarchicalClustering_Clustering = ["clustering"]
HistGradientBoostingClassifier_MLJScikitLearnInterface = ["classification"]
HistGradientBoostingRegressor_MLJScikitLearnInterface = ["regression"]
HuberRegressor_MLJLinearModels = ["regression"]
HuberRegressor_MLJScikitLearnInterface = ["regression"]
ICA_MultivariateStats = ["encoders"]
IForestDetector_OutlierDetectionPython = ["outlier_detection"]
ImageClassifier_MLJFlux = ["classification", "image_processing", "iterative_models"]
INNEDetector_OutlierDetectionPython = ["outlier_detection"]
InteractionTransformer_MLJModels = ["static_models", "feature_engineering"]
IteratedModel_MLJIteration = ["iterative_models", "meta_algorithms"]
KDEDetector_OutlierDetectionPython = ["outlier_detection"]
KMeansClusterer_BetaML = ["clustering"]
KMeans_Clustering = ["clustering", "dimension_reduction", ]
KMeans_ParallelKMeans = ["clustering", "dimension_reduction", ]
KMeans_MLJScikitLearnInterface = ["clustering", "dimension_reduction", ]
KMedoidsClusterer_BetaML = ["clustering"]
KMedoids_Clustering = ["clustering", "dimension_reduction", ]
KNNClassifier_NearestNeighborModels = ["classification"]
KNNDetector_OutlierDetectionNeighbors = ["outlier_detection"]
KNNDetector_OutlierDetectionPython = ["outlier_detection"]
KNNRegressor_NearestNeighborModels = ["regression"]
KNeighborsClassifier_MLJScikitLearnInterface = ["classification"]
KNeighborsRegressor_MLJScikitLearnInterface = ["regression"]
KPLSRegressor_PartialLeastSquaresRegressor = ["regression"]
KernelPCA_MultivariateStats = ["dimension_reduction", ]
KernelPerceptronClassifier_BetaML = ["classification", "neural_networks"]
LADRegressor_MLJLinearModels = ["regression"]
LDA_MultivariateStats = ["classification", "dimension_reduction", ]
LGBMClassifier_LightGBM = ["classification", "ensemble_models", "iterative_models"]
LGBMRegressor_LightGBM = ["regression", "ensemble_models", "iterative_models"]
LMDDDetector_OutlierDetectionPython = ["outlier_detection", "outlier_detection"]
LOCIDetector_OutlierDetectionPython = ["outlier_detection"]
LODADetector_OutlierDetectionPython = ["outlier_detection"]
LOFDetector_OutlierDetectionNeighbors = ["outlier_detection"]
LOFDetector_OutlierDetectionPython = ["outlier_detection"]
LarsCVRegressor_MLJScikitLearnInterface = ["regression"]
LarsRegressor_MLJScikitLearnInterface = ["regression"]
LassoCVRegressor_MLJScikitLearnInterface = ["regression"]
LassoLarsCVRegressor_MLJScikitLearnInterface = ["regression"]
LassoLarsICRegressor_MLJScikitLearnInterface = ["regression"]
LassoLarsRegressor_MLJScikitLearnInterface = ["regression"]
LassoRegressor_MLJLinearModels = ["regression"]
LassoRegressor_MLJScikitLearnInterface = ["regression"]
LinearBinaryClassifier_GLM = ["classification"]
LinearCountRegressor_GLM = ["regression"]
LinearRegressor_GLM = ["regression"]
LinearRegressor_MLJLinearModels = ["regression"]
LinearRegressor_MultivariateStats = ["regression"]
LinearRegressor_MLJScikitLearnInterface = ["regression"]
LinearSVC_LIBSVM = ["classification"]
LogisticCVClassifier_MLJScikitLearnInterface = ["classification"]
LogisticClassifier_MLJLinearModels = ["classification"]
LogisticClassifier_MLJScikitLearnInterface = ["classification"]
MCDDetector_OutlierDetectionPython = ["outlier_detection", "outlier_detection"]
MeanShift_MLJScikitLearnInterface = ["clustering"]
MiniBatchKMeans_MLJScikitLearnInterface = ["clustering", "dimension_reduction", ]
MultiTaskElasticNetCVRegressor_MLJScikitLearnInterface = ["regression"]
MultiTaskElasticNetRegressor_MLJScikitLearnInterface = ["regression"]
MultiTaskLassoCVRegressor_MLJScikitLearnInterface = ["regression"]
MultiTaskLassoRegressor_MLJScikitLearnInterface = ["regression"]
MultinomialClassifier_MLJLinearModels = ["classification"]
MultinomialNBClassifier_NaiveBayes = ["classification", "Bayesian_models"]
MultinomialNBClassifier_MLJScikitLearnInterface = ["classification", "Bayesian_models"]
MultitargetGaussianMixtureRegressor_BetaML = ["regression", "density_estimation"]
MultitargetKNNClassifier_NearestNeighborModels = ["classification"]
MultitargetKNNRegressor_NearestNeighborModels = ["regression"]
MultitargetLinearRegressor_MultivariateStats = ["regression"]
MultitargetNeuralNetworkRegressor_BetaML = ["regression", "neural_networks"]
MultitargetNeuralNetworkRegressor_MLJFlux = ["regression", "iterative_models", "neural_networks"]
MultitargetRidgeRegressor_MultivariateStats = ["regression"]
MultitargetSRRegressor_SymbolicRegression = ["regression"]
NeuralNetworkBinaryClassifier_MLJFlux = ["classification", "neural_networks"]
NeuralNetworkClassifier_BetaML = ["classification", "neural_networks"]
NeuralNetworkClassifier_MLJFlux = ["classification", "iterative_models", "neural_networks"]
NeuralNetworkRegressor_BetaML = ["regression", "neural_networks"]
NeuralNetworkRegressor_MLJFlux = ["regression", "iterative_models", "neural_networks"]
NuSVC_LIBSVM = ["classification"]
NuSVR_LIBSVM = ["regression"]
OCSVMDetector_OutlierDetectionPython = ["outlier_detection"]
OPTICS_MLJScikitLearnInterface = ["clustering", "static_models"]
OneClassSVM_LIBSVM = ["outlier_detection"]
OneHotEncoder_MLJModels = ["encoders"]
OneRuleClassifier_OneRule = ["classification"]
OrthogonalMatchingPursuitCVRegressor_MLJScikitLearnInterface = ["regression"]
OrthogonalMatchingPursuitRegressor_MLJScikitLearnInterface = ["regression"]
PCA_MultivariateStats = ["dimension_reduction", ]
PCADetector_OutlierDetectionPython = ["outlier_detection"]
PLSRegressor_PartialLeastSquaresRegressor = ["regression"]
PPCA_MultivariateStats = ["dimension_reduction"]
PartLS_PartitionedLS = ["regression"]
PassiveAggressiveClassifier_MLJScikitLearnInterface = ["classification"]
PassiveAggressiveRegressor_MLJScikitLearnInterface = ["regression"]
PegasosClassifier_BetaML = ["classification"]
PerceptronClassifier_BetaML = ["classification", "iterative_models", "neural_networks"]
PerceptronClassifier_MLJScikitLearnInterface = ["classification", "iterative_models", "neural_networks"]
Pipeline_MLJBase = ["meta_algorithms"]
ProbabilisticNuSVC_LIBSVM = ["classification"]
ProbabilisticSGDClassifier_MLJScikitLearnInterface = ["classification"]
ProbabilisticSVC_LIBSVM = ["classification"]
QuantileRegressor_MLJLinearModels = ["regression"]
RandomOversampler_Imbalance = ["class_imbalance"]
RandomUndersampler_Imbalance = ["class_imbalance"]
RandomWalkOversampler_Imbalance = ["class_imbalance"]
RANSACRegressor_MLJScikitLearnInterface = ["regression"]
RODDetector_OutlierDetectionPython = ["outlier_detection"]
ROSE_Imbalance = ["class_imbalance"]
RandomForestClassifier_BetaML = ["classification", "ensemble_models", "iterative_models"]
RandomForestClassifier_DecisionTree = ["classification", "ensemble_models", "iterative_models"]
RandomForestClassifier_MLJScikitLearnInterface = ["classification", "ensemble_models", "iterative_models"]
RandomForestImputer_BetaML = ["missing_value_imputation", "ensemble_models", "iterative_models"]
RandomForestRegressor_BetaML = ["regression", "ensemble_models", "iterative_models"]
RandomForestRegressor_DecisionTree = ["regression", "ensemble_models", "iterative_models"]
RandomForestRegressor_MLJScikitLearnInterface = ["regression", "ensemble_models", "iterative_models"]
RecursiveFeatureElimination_FeatureSelection = ["dimension_reduction", "meta_algorithms", "feature_engineering"]
Resampler_MLJBase = ["meta_algorithms"]
RidgeCVClassifier_MLJScikitLearnInterface = ["classification"]
RidgeCVRegressor_MLJScikitLearnInterface = ["classification"]
RidgeClassifier_MLJScikitLearnInterface = ["classification"]
RidgeRegressor_MLJLinearModels = ["regression"]
RidgeRegressor_MultivariateStats = ["regression"]
RidgeRegressor_MLJScikitLearnInterface = ["regression"]
RobustRegressor_MLJLinearModels = ["regression"]
SelfOrganizingMap_SelfOrganizingMaps = ["dimension_reduction", "clustering"]
SGDClassifier_MLJScikitLearnInterface = ["classification"]
SGDRegressor_MLJScikitLearnInterface = ["regression"]
SMOTE_Imbalance = ["class_imbalance"]
SMOTEN_Imbalance = ["class_imbalance"]
SMOTENC_Imbalance = ["class_imbalance"]
SODDetector_OutlierDetectionPython = ["outlier_detection", "outlier_detection"]
SOSDetector_OutlierDetectionPython = ["outlier_detection"]
SRRegressor_SymbolicRegression = ["regression"]
StableForestClassifier_SIRUS = ["classification"]
StableForestRegressor_SIRUS = ["regression"]
StableRulesClassifier_SIRUS = ["classification"]
StableRulesRegressor_SIRUS = ["regression"]
Stack_MLJBase = ["meta_algorithms", "ensemble_models"]
SVC_LIBSVM = ["classification"]
SVMClassifier_MLJScikitLearnInterface = ["classification"]
SVMLinearClassifier_MLJScikitLearnInterface = ["classification"]
SVMLinearRegressor_MLJScikitLearnInterface = ["regression"]
SVMNuClassifier_MLJScikitLearnInterface = ["classification"]
SVMNuRegressor_MLJScikitLearnInterface = ["regression"]
SVMRegressor_MLJScikitLearnInterface = ["regression"]
SimpleImputer_BetaML = ["missing_value_imputation"]
SpectralClustering_MLJScikitLearnInterface = ["clustering", "static_models"]
Standardizer_MLJModels = ["encoders"]
SubspaceLDA_MultivariateStats = ["classification", "dimension_reduction"]
TomekUndersampler_Imbalance = ["class_imbalance"]
TunedModel_MLJTuning = ["meta_algorithms"]
TSVDTransformer_TSVD = ["dimension_reduction"]
TfidfTransformer_MLJText = ["encoders", "text_analysis"]
TheilSenRegressor_MLJScikitLearnInterface = ["regression"]
TransformedTargetModel_MLJBase = ["meta_algorithms", "outlier_detection"]
UnivariateBoxCoxTransformer_MLJModels = ["encoders"]
UnivariateDiscretizer_MLJModels = ["encoders"]
UnivariateFillImputer_MLJModels = ["missing_value_imputation"]
UnivariateStandardizer_MLJModels = ["encoders"]
UnivariateTimeTypeToContinuous_MLJModels = ["encoders"]
XGBoostClassifier_XGBoost = ["classification", "iterative_models", "ensemble_models"]
XGBoostCount_XGBoost = ["regression", "iterative_models", "ensemble_models"]
XGBoostRegressor_XGBoost = ["regression", "iterative_models", "ensemble_models"]
